# Generated by Django 6.0.6 on 2026-06-30 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherForcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_alerts', models.BooleanField(default=False)),
                ('daily_forecast', models.BooleanField(default=False)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
